### ISSUE TITLE
Improve order view

### ISSUE THREAD

**Issue by madmooose** [bruecksen/bakeup#109]
- [x] Invert ordering
- [x] add delete button for order
- [x] show if orders are already planned
- [x] add/update planning button for products
- [x] add plan all (for one day)
- [x] add function to add customer orders (also for stuff member if you want some extra ones)
- [x] add editing of customer orders (does not respect max order quantity)
- [x] let staff override max order quantity
- [x] make production days visible/invisible
- [x] make updating production plan only possible if in the past

**Comment by bruecksen** [comment]
@madmooose I added an update button to the production plan list, and an delete button to the order list view. More to come tonight ::)) please have go.
