### ISSUE TITLE
Add batch orders and editing (as a preversion of the abos)

### ISSUE THREAD

**Issue by madmooose** [bruecksen/bakeup#128]
- [x] Make a table-view of all customers and producible products for one baking day
- [ ] add customer filter (ex. depos)
- [x] read already placed orders
- [ ] ~~make orders changeable with dropdown~~ makes no sense to stupid me
- [ ] add button to adjust max order quantity
- [x] add button to regenerate production plan

see also #138 for bugs

**Comment by madmooose** [comment]
Here we want to make orders for customers in a batch view. Simplest approach is to list all customers and products of a production day like this:
|customer  |product 1|product 2|product3|
|--------------|-------------|------------|------------|
|customer 1|value field|value field|value field|
|customer 2|value field|value field|value field|
|customer 3|value field|value field|value field|

**Comment by bruecksen** [comment]
@madmooose I added an batch add order view. Its working great, please have a look :) Also production day list view is improved a lot and there is a production day detail view

**Comment by bruecksen** [comment]
@madmooose the batch order view doesn't look on the max order quantities. It allows all the nasty things.

**Comment by madmooose** [comment]
@bruecksen if order amount is zero it should show 0 and not quantity
