### ISSUE TITLE
Add State to production plans

### ISSUE THREAD

**Issue by bruecksen** [bruecksen/bakeup#132]
We add a state to the production plans:

- [x]  0 = planned
1 = in_production
2 = produced
3 = canceled
(see also https://github.com/bruecksen/bakeup/issues/132#issuecomment-1279919510)

- [x] as soon as attached production plan reaches state >0 oders get locked

**Comment by madmooose** [comment]
Sounds like the rebirth of the archive flag

Am 28. September 2022 17:47:35 MESZ schrieb "Matthias Brück" ***@***.***>:
>It would be nice to mark a production plan as done, so that we can filter out all the old plans and put them into an archive. what do you think @madmooose ?
>
>-- 
>Reply to this email directly or view it on GitHub:
>https://github.com/bruecksen/bakeup/issues/132
>You are receiving this because you were mentioned.
>
>Message ID: ***@***.***>
-- mobil gesendet
Niels Göttsch
Gut Hemmelmark 5
24360 Barkelsby

**Comment by madmooose** [comment]
#131 is locked as soon as planning state is higher than 0

**Comment by bruecksen** [comment]
@madmooose there is now a state but we only show it at the moment. we now need to use it at the different views. will come soon.

**Comment by madmooose** [comment]
I would like to suggest to add another step
0 = draft
1 = planned
2 = in_production
3 = produced
4 = canceled

**Comment by madmooose** [comment]
If you hit start in the production plan you get a 500.
