### ISSUE TITLE
It is possible to create production day with the same date

### ISSUE THREAD

**Issue by madmooose** [bruecksen/bakeup#133]
Reproduce:
Got to production day -> add production day -> choose a already chosen day -> hit create production day

Solution:
this should be prohibited on ORM/Database layer

**Comment by madmooose** [comment]
hmm this problem seems to be only related to old production days (like 19.8.2022 on niels databse)

**Comment by bruecksen** [comment]
@madmooose yes this shouldn't work. please delete your old production days :)
