### ISSUE TITLE
updating orders buglist

### ISSUE THREAD

**Issue by madmooose** [bruecksen/bakeup#138]
workshop/orders/5/update/ (if you come from order -> edit order)
- [ ] We don't need the add product button here. I think listing all available products for that day is fine and it avoids the double choice problem.
- [ ] updating doesn't do anything here workshop/orders/5/update/
- [ ] I would suggest to skip that function at all and use a filter on /add for users. maybe we need other layouting than.

/workshop/orders/add/9/ (if you come from production days)
- [ ] Users can be fixed here. no need for a dropdown.
- [ ] suggestion would be to fix the username at the front and make products horizontal scrollable (if it doesn't fit the screen)

- [ ] we should update/delete production plan on order change

**Comment by bruecksen** [comment]
@madmooose i don't understand most of the points, please clarify :)
