### ISSUE TITLE
i can delete a product on production day that has orders

### ISSUE THREAD

**Issue by madmooose** [bruecksen/bakeup#139]
- [x] orders should not ne deleteable on orm level if they have production plan
- [x] production day entries should not be deleteable if the have orders
- [x] we should warn when deleting a product that has orders
- [x] we should delete all related orders on deleting the product if no production plan exists
- [x] if production plan already exists put it in state canceled #132

**Comment by bruecksen** [comment]
@madmooose I added some checks that protects objects from deletion. Deleting a product that has orders is simply not possible (its protetected by the orm with an check). I would like to keep it that way for the moment.
