### ISSUE TITLE
Improve shop

### ISSUE THREAD

**Issue by madmooose** [bruecksen/bakeup#142]
In order for people how want to order for our upcoming bakeup party to order in advance (more than a week) we need an improved view on the shop. This is basically a summery of the call I had with @bruecksen yesterday.

- [x] skip the overview/menu in shop for now
- [x] remove/hide abo and order menu for now
- [x] introduce daily view and make it default 
- [x] always jump to the next upcoming bakingday as default
- [x] show a message if no baking days are planned in the future
- [x] ignore empty days

**Comment by bruecksen** [comment]
@madmooose shop improved ::))
