### ISSUE TITLE
OrderPosition should contain all necessary information about the product and price

### ISSUE THREAD

**Issue by bruecksen** [bruecksen/bakeup#158]
We need to store all relevant information about the product directly in the OrderPosition. So that we have the information even though the product got changed in the meantime.

**Comment by madmooose** [comment]
Should not be the case as products of an order are a copy of the original.

Am 7. März 2023 13:50:04 MEZ schrieb "Matthias Brück" ***@***.***>:
>We need to store all relevant information about the product directly in the OrderPosition. So that we have the information even though the product got changed in the meantime.
>
>-- 
>Reply to this email directly or view it on GitHub:
>https://github.com/bruecksen/bakeup/issues/158
>You are receiving this because you are subscribed to this thread.
>
>Message ID: ***@***.***>
-- mobil gesendet
Niels Göttsch
Gut Hemmelmark 5
24360 Barkelsby
+49 177 196 1512

**Comment by bruecksen** [comment]
@madmooose no not at the moment. And I don't if that is the direction we should go because it would mean that every order creates a copy of an product. We could use the production plan products though. But this would require that the plan is created when the production day product is added.

**Comment by madmooose** [comment]
OK, than lets review workflow here to get it right

Am 7. März 2023 14:07:24 MEZ schrieb "Matthias Brück" ***@***.***>:
>@madmooose no not at the moment. And I don't if that is the direction we should go because it would mean that every order creates a copy of an product. We could use the production plan products though. But this would require that the plan is created when the production day product is added. 
>
>-- 
>Reply to this email directly or view it on GitHub:
>https://github.com/bruecksen/bakeup/issues/158#issuecomment-1458140190
>You are receiving this because you were mentioned.
>
>Message ID: ***@***.***>
-- mobil gesendet
Niels Göttsch
Gut Hemmelmark 5
24360 Barkelsby
+49 177 196 1512

**Comment by bruecksen** [comment]
this is now the case.
