### ISSUE TITLE
Add Preview of delivery bill during production

### ISSUE THREAD

**Issue by ollo2012** [bruecksen/bakeup#189]
Make the Delivery Bill Preview updateable or check changes made in "edit orders/order managment"

**Comment by bruecksen** [comment]
@ollo2012 there is now a preview of the delivery bill if a production plan is present and the plan is not cancelled. The state of the product is shown on the delivery bill but only if it is not produced. Also an order gets automatically added to an existing production plan, and so to the deilvery bill if added/updated.
