### ISSUE TITLE
Add recipes

### ISSUE THREAD

**Issue by bruecksen** [bruecksen/bakeup#23]

**Comment by madmooose** [comment]
- we need conventional categories for view aggregation: flour, salt, pre-dough, liquids, (dried fruits, nuts)
- pre-dought should be 1 kg by convention
- lock editing of pre-dough if used more than 1 time
- should we treat categorized products as hidden?
- if product has a weight, we should against hierarchy weight
- if products have infinite loop (like sourdough starter), ignore product reference as ratio doesn't change

**Comment by madmooose** [comment]
![image1](https://user-images.githubusercontent.com/31863594/164217961-62dcabe1-b77c-4744-9fd5-639bc081e553.png)
