### ISSUE TITLE
User, User Profile deletion

### ISSUE THREAD

**Issue by bruecksen** [bruecksen/bakeup#242]
@madmooose how should we handle user, user profile deletion. Would it be enough to just deactivate the user account (set is_active flag to False) or do we need to delete the user and all related data?

**Comment by madmooose** [comment]
Deletion is no option.
I would offer two options. **Deactivate** and delete
- Deactivate sets is_active to false
- delete sets is_active to false and zeros all data fields

Am 8. Juni 2023 11:38:31 MESZ schrieb "Matthias Brück" ***@***.***>:
>@madmooose how should we handle user, user profile deletion. Would it be enough to just deactivate the user account (set is_active flag to False) or do we need to delete the user and all related data?
>
>-- 
>Reply to this email directly or view it on GitHub:
>https://github.com/bruecksen/bakeup/issues/242
>You are receiving this because you were mentioned.
>
>Message ID: ***@***.***>
-- mobil gesendet
Niels Göttsch
Gut Hemmelmark 5
24360 Barkelsby

**Comment by bruecksen** [comment]
@madmooose 
> and zeros all data fields
and so after this an order would exist without user. But this would mean we would need to store the user information about the order separtely, otherwise we would have orders without this information...

**Comment by bruecksen** [comment]
Lutz

> Und bleiben uns die Kundendaten auch erhalten, selbst wenn ein Kunde den Account löscht, bevor wir eine Rechnung geschrieben haben? Vielleicht wäre es eine Überlegung wert, dass die Kunden Ihren Account nicht selbst löschen können, sondern das per Buttonklick beantragen müssen und wir prüfen dann, ob noch Zahlungen offen sind. Den Account löschen wir dann manuell, sobald die Zahlung eingegangen ist

**Comment by madmooose** [comment]
Deleting profiles is mit trivial at all. We already discussed that but I don't know the conclusion anymore. For now I would just delete login data.

Am 23. August 2023 09:47:13 MESZ schrieb "Matthias Brück" ***@***.***>:
>Lutz
>
>> Und bleiben uns die Kundendaten auch erhalten, selbst wenn ein Kunde den Account löscht, bevor wir eine Rechnung geschrieben haben? Vielleicht wäre es eine Überlegung wert, dass die Kunden Ihren Account nicht selbst löschen können, sondern das per Buttonklick beantragen müssen und wir prüfen dann, ob noch Zahlungen offen sind. Den Account löschen wir dann manuell, sobald die Zahlung eingegangen ist
>
>-- 
>Reply to this email directly or view it on GitHub:
>https://github.com/bruecksen/bakeup/issues/242#issuecomment-1689456624
>You are receiving this because you were mentioned.
>
>Message ID: ***@***.***>
-- mobil gesendet
Niels Göttsch
Gut Hemmelmark 5
24360 Barkelsby

**Comment by bruecksen** [comment]
@madmooose yes, i would like to make it possible to deactivate the account in the first place (`is_active=False`). For user data deletion the user needs to write to the client ok?

**Comment by madmooose** [comment]
Yes, and in this case I still won't delete metadata but rather override values of the profile. 

Am 23. August 2023 09:55:33 MESZ schrieb "Matthias Brück" ***@***.***>:
>@madmooose yes, i would like to make it possible to deactivate the account in the first place (`is_active=False`). For user data deletion the user needs to write to the client ok?
>
>-- 
>Reply to this email directly or view it on GitHub:
>https://github.com/bruecksen/bakeup/issues/242#issuecomment-1689468695
>You are receiving this because you were mentioned.
>
>Message ID: ***@***.***>
-- mobil gesendet
Niels Göttsch
Gut Hemmelmark 5
24360 Barkelsby
