### ISSUE TITLE
Newsletter campaigns

### ISSUE THREAD

**Issue by bruecksen** [bruecksen/bakeup#244]
as discussed with ole today it would be great to create email/newsletter campaigns from within wagtail. There is a wagtail package wagtail-birdsong https://github.com/neon-jungle/wagtail-birdsong wich could be a good starting point. It even uses https://mjml.io/ for writing responsive email templates. Lets check if this is a way we want't to go.

**Comment by madmooose** [comment]
Merge with #235

**Comment by bruecksen** [comment]
closing in favor of #274
