### ISSUE TITLE
Add multiple same product to production day

### ISSUE THREAD

**Issue by bruecksen** [bruecksen/bakeup#245]
- [ ] remove constraint
- [ ] sum product for production plan
- [ ] add comment to productiondayproduct
- [ ] show comment on delivery bill and productiondaydetail

**Comment by bruecksen** [comment]
we need this for #175 right?

**Comment by madmooose** [comment]
Yes, indeed.

Am 23. August 2023 09:43:11 MESZ schrieb "Matthias Brück" ***@***.***>:
>we need this for #175 right?
>
>-- 
>Reply to this email directly or view it on GitHub:
>https://github.com/bruecksen/bakeup/issues/245#issuecomment-1689451341
>You are receiving this because you are subscribed to this thread.
>
>Message ID: ***@***.***>
-- mobil gesendet
Niels Göttsch
Gut Hemmelmark 5
24360 Barkelsby

**Comment by bruecksen** [comment]
@madmooose ich mach mal schnell in deutsch weil das geht einfacher ;) Ich mache mir gerade gedanken zu #175 und wenn wir zweimal das gleiche Produkt einem Produktionstag zuordnen wie wir die Bestellungen auseinanderhalten können. Das brauchen wir ja um die maximale Bestellmenge pro Produkt sicher zu stellen. Brauchen wir vielleicht doch noch eine Beziehung einer Bestellposition zu einem ProductionDayProduct?

**Comment by madmooose** [comment]
Mhhh, das ist stimmt.
Bin dafür den Count über an die ProductionDayProduct angehängten SaleOrderLines zu machen.

**Comment by bruecksen** [comment]
@madmooose as discussed we will postpone this feature, and implement #175 without the option to add same product tiwce.
