### ISSUE TITLE
Make csv export files configurable per client

### ISSUE THREAD

**Issue by bruecksen** [bruecksen/bakeup#250]
@madmooose how should we do this, any thoughts? The requested csv file for lutz contains columns like `kundengruppe` with a fixed value. I don't wan't to have this in the general customer export and would instead make the columns configurable per client.

**Comment by madmooose** [comment]
AS discussed we do profiles for external POS systems but not customer specific formats

Am 22. Juni 2023 11:08:36 MESZ schrieb "Matthias Brück" ***@***.***>:
>@madmooose how should we do this, any thoughts? The requested csv file for lutz contains columns like `kundengruppe` with a fixed value. I don't wan't to have this in the general customer export and would instead make the columns configurable per client.
>
>-- 
>Reply to this email directly or view it on GitHub:
>https://github.com/bruecksen/bakeup/issues/250
>You are receiving this because you were mentioned.
>
>Message ID: ***@***.***>
-- mobil gesendet
Niels Göttsch
Gut Hemmelmark 5
24360 Barkelsby
