### ISSUE TITLE
Optimize the generation of the full ingredients list

### ISSUE THREAD

**Issue by bruecksen** [bruecksen/bakeup#267]
We should save a full ingredient list of a product if the hierarchy of the product gets changed and use this list in the frontend. The generation of the ingredient list is costly and makes the sortiments view very slow....

@madmooose any thoughts welcome :)

**Comment by madmooose** [comment]
Do it

Am 27. September 2023 15:02:45 MESZ schrieb "Matthias Brück" ***@***.***>:
>@madmooose this seems not to be a big performance problem at the moment, so i would like to close it for now and think about later .... :)
>
>-- 
>Reply to this email directly or view it on GitHub:
>https://github.com/bruecksen/bakeup/issues/267#issuecomment-1737358020
>You are receiving this because you were mentioned.
>
>Message ID: ***@***.***>
-- mobil gesendet
Niels Göttsch
Gut Hemmelmark 5
24360 Barkelsby

**Comment by bruecksen** [comment]
@madmooose nah, ich würde gerne, wenn wir uns an den rezept editor machen nochmal über die datenstruktur nachdenken und überlegen ob wir da nicht doch einen vernünftigen baum (django-treabeard) verwenden. Weil mein gefühl da nach wie vor ist das rad nicht unbedingt neu erfinden zu wollen. Damit sollte dann das erzeugen einer ingredient list auch super performant sein...

**Comment by madmooose** [comment]
OK! Do you create a 0.9 ticket?

Am 28. September 2023 09:29:40 MESZ schrieb "Matthias Brück" ***@***.***>:
>@madmooose nah, ich würde gerne, wenn wir uns an den rezept editor machen nochmal über die datenstruktur nachdenken und überlegen ob wir da nicht doch einen vernünftigen baum (django-treabeard) verwenden. Weil mein gefühl da nach wie vor ist das rad nicht unbedingt neu erfinden zu wollen. Damit sollte dann das erzeugen einer ingredient list auch super performant sein...
>
>-- 
>Reply to this email directly or view it on GitHub:
>https://github.com/bruecksen/bakeup/issues/267#issuecomment-1738623949
>You are receiving this because you were mentioned.
>
>Message ID: ***@***.***>
-- mobil gesendet
Niels Göttsch
Gut Hemmelmark 5
24360 Barkelsby
