### ISSUE TITLE
Meta product abo

### ISSUE THREAD

**Issue by bruecksen** [bruecksen/bakeup#272]
- [ ] We add the posibility to subscribe to a product on the product sortiment page.

Ole asks, How could a meta product abo be placed by a customer?

**Comment by madmooose** [comment]
Simply, it can't AS long AS its not public. If its public it can just AS every other product from the peoduct overview page 
Wie need to add a section here if we don't have it yet.

Am 14. August 2023 11:34:57 MESZ schrieb "Matthias Brück" ***@***.***>:
>Ole asks, How could a meta product abo be placed by a customer?
>
>-- 
>Reply to this email directly or view it on GitHub:
>https://github.com/bruecksen/bakeup/issues/272
>You are receiving this because you are subscribed to this thread.
>
>Message ID: ***@***.***>
-- mobil gesendet
Niels Göttsch
Gut Hemmelmark 5
24360 Barkelsby

**Comment by bruecksen** [comment]
closing in favor of #331
