### ISSUE TITLE
Create abo orders for abo products of exsiting future productiondays

### ISSUE THREAD

**Issue by bruecksen** [bruecksen/bakeup#273]

**Comment by bruecksen** [comment]
@madmooose lutz wants to have this, what do you think about it? It should be alright to add orders for and created abo to all public productionday products that are in planning state, right? But what if a abo quantity is changed later on?

**Comment by madmooose** [comment]
I think we already discussed that. 
When creating an abo
and future baking days exist
Then ASK the customer if he wants to apply abo to future baking days.

With current design, there is no way in changing future orders when changing abo. I'm also scared oft sie effects ex. too many orders. I wourld rather suggest to not publish to many baking days.

Am 17. August 2023 11:44:56 MESZ schrieb "Matthias Brück" ***@***.***>:
>@madmooose lutz wants to have this, what do you think about it? It should be alright to add orders for and created abo to all public productionday products that are in planning state, right? But what if a abo quantity is changed later on? 
>
>-- 
>Reply to this email directly or view it on GitHub:
>https://github.com/bruecksen/bakeup/issues/273#issuecomment-1681972223
>You are receiving this because you were mentioned.
>
>Message ID: ***@***.***>
-- mobil gesendet
Niels Göttsch
Gut Hemmelmark 5
24360 Barkelsby

**Comment by bruecksen** [comment]
@madmooose ok, that makes the whole thing much more complicated. I will think about it.

> I wourld rather suggest to not publish to many baking days. 

yes but lutz will do so i guess.
