### ISSUE TITLE
Make checkout modal not delete selected products

### ISSUE THREAD

**Issue by madmooose** [bruecksen/bakeup#287]
Current behavior:
When you close the checkout modal without sending the new order,
THEN all slected products are set to zero.

Expected behaviour:
WHEN you have selected some products
AND you open the checkout modal
AND close it for ordering more/change ammounts
THEN modal should close but amounts of selected values should stay the same as before entering the modal. (Changes made in the modal should be discarded.)

**Comment by bruecksen** [comment]
@madmooose thats already fixed....
