### ISSUE TITLE
Add translations

### ISSUE THREAD

**Issue by madmooose** [bruecksen/bakeup#289]
A lot of fields are not translatable yet.

**Comment by bruecksen** [comment]
@madmooose some little things i found:

missing space after icon:
![image](https://github.com/bruecksen/bakeup/assets/3972738/ffb7a559-17cd-473e-b2b2-6086e0c8c019)

Add/update production day (e.g. https://staging.bakeup.org/workshop/production-days/32/update/?next=/workshop/production-days/32/)
![image](https://github.com/bruecksen/bakeup/assets/3972738/0f96f0b2-1405-4d4c-8886-96b36034e460)

**Comment by madmooose** [comment]
both fixed on staging

**Comment by bruecksen** [comment]
there is a followup issue in #356
