### ISSUE TITLE
django-money raises error because of language variant

### ISSUE THREAD

**Issue by bruecksen** [bruecksen/bakeup#292]
https://brueckio.sentry.io/issues/4415797335/?project=6247206&query=is%3Aunresolved&referrer=issue-stream&stream_index=0

[Errno 2] No such file or directory: '/home/django/djangoenv/lib/python3.10/site-packages/babel/locale-data/de_DE@Formal.dat'

I installed a hacky hack, and simply copied the de_DE file so that it is there. @madmooose do you understand why this only crashes on production and not on the staging and local env?

**Comment by madmooose** [comment]
No idea. Fürther investigation needed.

Am 23. August 2023 21:41:23 MESZ schrieb "Matthias Brück" ***@***.***>:
>https://brueckio.sentry.io/issues/4415797335/?project=6247206&query=is%3Aunresolved&referrer=issue-stream&stream_index=0
>
>[Errno 2] No such file or directory: ***@***.***'
>
>I installed a hacky hack, and simply copied the de_DE file so that it is there. @madmooose do you understand why this only crashes on production and not on the staging and local env?
>
>-- 
>Reply to this email directly or view it on GitHub:
>https://github.com/bruecksen/bakeup/issues/292
>You are receiving this because you were mentioned.
>
>Message ID: ***@***.***>
-- mobil gesendet
Niels Göttsch
Gut Hemmelmark 5
24360 Barkelsby

**Comment by bruecksen** [comment]
we are not the only one having problems with language variants and babel. I pinned the babel package version to a slightly older version, and this seems to work. The newer version doesn't ignore the language variant, but still lacks of a full support for it (https://github.com/python-babel/babel/issues/454)
