### ISSUE TITLE
When creating an inline product, amount must be checked

### ISSUE THREAD

**Issue by madmooose** [bruecksen/bakeup#298]
![grafik](https://github.com/bruecksen/bakeup/assets/31863594/f8d158aa-bbdb-43d7-80da-46c5e5350e62)
When you fill everything execpt weight, it crashes.

**Comment by bruecksen** [comment]
@madmooose das tut jetzt. Die stelle ist nach wie vor hakelig, aber immerhin das funktioniert jetzt und es gibt eine Meldung wenn die Kategorie fehlt. Das sollte natürlich idealerweise früher abgefangen werden aber das erfordert etwas js.
