### ISSUE TITLE
Make datepicker pick up locale/language, default de, and start with mondays

### ISSUE THREAD

**Issue by bruecksen** [bruecksen/bakeup#314]

**Comment by madmooose** [comment]
I reopen this issue, so wie can solve this properly in our maintenace release. 
@bruecksen don't forget to merge to stageing first.

**Comment by bruecksen** [comment]
> @bruecksen don't forget to merge to stageing first.

it is on staging...

**Comment by madmooose** [comment]
Ok, then i've overlooked PR. Sorry to bother you

Am 30. August 2023 13:50:24 MESZ schrieb "Matthias Brück" ***@***.***>:
>> @bruecksen don't forget to merge to stageing first.
>
>it is on staging...
>
>
>-- 
>Reply to this email directly or view it on GitHub:
>https://github.com/bruecksen/bakeup/issues/314#issuecomment-1699016054
>You are receiving this because you modified the open/close state.
>
>Message ID: ***@***.***>
-- mobil gesendet
Niels Göttsch
Gut Hemmelmark 5
24360 Barkelsby

**Comment by bruecksen** [comment]
> then i've overlooked PR.

I don't always open a PR and i usually do it only for main. Otherwise I simply merge the branch into staging and deploy. I think that is ok, right? A PR feels slightly overdose If its just 1 commit, no discussion and its merged directly....
