### ISSUE TITLE
Add allergies

### ISSUE THREAD

**Issue by madmooose** [bruecksen/bakeup#33]
- create separate model  like: product|name|color|
- add get_allergies method to product to crawl through hierarchy

**Comment by bruecksen** [comment]
> Im Bakeup-Backend können Produkte/Inhaltsstoffe als Allergene gekennzeichnet werden. Dadurch werden die Inhaltsstoffe im Shop in der Zutatenliste ggf. zusätzlich als Allergene gekennzeichnet.

**Comment by bruecksen** [comment]
we do this by using all caps on the product names
