### ISSUE TITLE
Make recipe view/template nice and shiny

### ISSUE THREAD

**Issue by bruecksen** [bruecksen/bakeup#38]
related #56 #55 

- [x]  normalize everything thats composable to 1kg to make it not change recipe rations in other recipes, maybe add button for now #87 
- [x] allow 0,1 steps as gram value, make a clever rounding in the template drop digits if not important
- [x] add baker percentages
- [x] make keyfacts readonly
- [x] make add recipes nice, inline add products

**Comment by madmooose** [comment]
Add history view:
- #59 is needed for that

**Comment by madmooose** [comment]
https://github.com/bruecksen/bakeup/issues/23#issuecomment-1103808693

**Comment by madmooose** [comment]
First attempt addressing every field:
1. we need a method to generate a structure like that ingredient_sum = ( category of product:[(product_name:amount) , ...])
2. we need a filter-posibility for that method like this ingredient_pre-dough_sum = filter(object.parents.child.category.slug == "pre-dough") to gather just the amounts under the pre-doughts.
3. now we can fetch total_flour, total_liquid and total_salt from ingredient_sum
4. now we can fetch total_flour_pre-dough from ingredient_pre-dough_sum
5. flour: for every category in cartegory==flour do ingredient_sum(sum_amounts(category))/total_flour
6. starter: for every category in category==starter show category (with products in case of sourdough???)
7. pre-fermented flour: total_flour_pre-dough / total_flour
8. salt: ingredient_sum['salt']
9. hydration: total_liquids/total_flour  or german TA: (total_liquids + total_flour)/total_flour * 100

tbc

**Comment by bruecksen** [comment]
- [ ] add classifier to categories (is_flour, is_,liquid, is_fat, is_salt)

**Comment by madmooose** [comment]
![IMG_20220525_110526](https://user-images.githubusercontent.com/31863594/170225661-4743e3b3-7ded-4f54-8fa8-da44530fc23a.jpg)

**Comment by madmooose** [comment]
![IMG_20220525_111943](https://user-images.githubusercontent.com/31863594/170228591-8ccf2c8e-ebc9-4255-8561-2c643e48c357.jpg)

**Comment by madmooose** [comment]
Netto-Teigausbeute = wasser / Mehl + 1
Brutto-Teigausbeite = (alle zutaten ausser mehl)/mehl + 1
Bäckerprozent = zutat/mehlmenge

**Comment by bruecksen** [comment]
@madmooose wir brauchen aber nur die Netto Teigausbeute oder? Was anderes zeigen wir ja nicht an...

**Comment by madmooose** [comment]
Ich denke am Ende wird es ein toggleswitch geben, aber eins nach dem anderen.

**Comment by madmooose** [comment]
User story/Feedback:
- we need the TA as a fuction to recalculate the amount of liquids.
- This fiction has to keep track of the total weight that should be normalized to 1kg.
- this function has to recalculate the predough to keep the versäuerung. This is probably all handled by the normalization method
