### ISSUE TITLE
Deleted products still exist in productionplan

### ISSUE THREAD

**Issue by ollo2012** [bruecksen/bakeup#394]

**Comment by madmooose** [comment]
You mean, deleted in produktion plan, right?

Am 29. Oktober 2023 21:04:14 MEZ schrieb ollo2012 ***@***.***>:
>
>
>-- 
>Reply to this email directly or view it on GitHub:
>https://github.com/bruecksen/bakeup/issues/394
>You are receiving this because you are subscribed to this thread.
>
>Message ID: ***@***.***>
-- mobil gesendet
Niels Göttsch
Gut Hemmelmark 5
24360 Barkelsby

**Comment by ollo2012** [comment]
I mean deleted in productionday-editing.

**Comment by bruecksen** [comment]
@madmooose @ollo2012 das funktioniert jetzt. Ist immer noch etwas holprig da zuerst immer die möglicherweise existierenden Bestellungen gelöscht werden müssen, aber dann löscht er jetzt das ProductionDayProduct und den dazugehörigen ProductionPlan.

**Comment by madmooose** [comment]
Das finde ich aber OK. So ist einem wenigstens bewusst, das man in die historie eingreift und wie.

Am 20. Februar 2024 03:16:16 MEZ schrieb "Matthias Brück" ***@***.***>:
>@madmooose @ollo2012 das funktioniert jetzt. Ist immer noch etwas holprig da zuerst immer die möglicherweise existierenden Bestellungen gelöscht werden müssen, aber dann löscht er jetzt das ProductionDayProduct und den dazugehörigen ProductionPlan.
>
>-- 
>Reply to this email directly or view it on GitHub:
>https://github.com/bruecksen/bakeup/issues/394#issuecomment-1953379610
>You are receiving this because you were mentioned.
>
>Message ID: ***@***.***>
-- mobil gesendet
Niels Göttsch
Gut Hemmelmark 5
24360 Barkelsby
