### ISSUE TITLE
ProductionPlan locked? if status == canceled

### ISSUE THREAD

**Issue by bruecksen** [bruecksen/bakeup#442]
@madmooose bei den ProductionPlans haben wir ja eine Logik die prüft ob der status > 0 ist und wenn ja ist der Plan locked. Cancelled fällt dort aber auch darunter (CANCELED = 3). Macht das sinn? Irgendwie denke ich canceled sollte nicht locked sein. Weil dann könnten Bestellungen gelöscht werden die einem canceled plan zugeordnet sind.

**Comment by madmooose** [comment]
Ich denke, Bestellungen sollten nach Möglichkeit erhalten bleiben, wegen der Nachvollziehbarkeit. Da an einen Canceled plan, nichts mehr geändert werden kann, sehe ich eigentlich keinen Grund sie zu löschen oder ändern. 

Am 20. Februar 2024 03:00:49 MEZ schrieb "Matthias Brück" ***@***.***>:
>@madmooose bei den ProductionPlans haben wir ja eine Logik die prüft ob der status > 0 ist und wenn ja ist der Plan locked. Cancelled fällt dort aber auch darunter (CANCELED = 3). Macht das sinn? Irgendwie denke ich canceled sollte nicht locked sein. Weil dann könnten Bestellungen gelöscht werden die einem canceled plan zugeordnet sind.
>
>-- 
>Reply to this email directly or view it on GitHub:
>https://github.com/bruecksen/bakeup/issues/442
>You are receiving this because you were mentioned.
>
>Message ID: ***@***.***>
-- mobil gesendet
Niels Göttsch
Gut Hemmelmark 5
24360 Barkelsby

**Comment by bruecksen** [comment]
@madmooose danke, dann kann das hier wieder zu.
