### ISSUE TITLE
[bug] separate buttons in production plan on small devices

### ISSUE THREAD

**Issue by madmooose** [bruecksen/bakeup#473]
![Screenshot_20240524-080214](https://github.com/bruecksen/bakeup/assets/31863594/cfee8211-ba95-4cc4-9fd1-6dfc59c184f3)
If we put the buttons at the top of the box it will also fit for small screens.
Same applies for the dashboard. Should we be able to control this from there at all. I would be fine with removing the buttons there.

**Comment by bruecksen** [comment]
@madmooose auch hier verstehe ich es nicht ganz. Was meinst du mit Box? ich vermute es geht um die Buttons Fertigstellen/Abbrechen auf Ebene der Produktionspläne?

**Comment by madmooose** [comment]
Genau. Guck dir das mal auf dem Telefon an. Dann siehst du, was ich meine.

Am 29. Mai 2024 08:43:22 MESZ schrieb "Matthias Brück" ***@***.***>:
>@madmooose auch hier verstehe ich es nicht ganz. Was meinst du mit Box? ich vermute es geht um die Buttons Fertigstellen/Abbrechen auf Ebene der Produktionspläne?
>
>-- 
>Reply to this email directly or view it on GitHub:
>https://github.com/bruecksen/bakeup/issues/473#issuecomment-2136653660
>You are receiving this because you were mentioned.
>
>Message ID: ***@***.***>
-- mobil gesendet
Niels Göttsch
Gut Hemmelmark 5
24360 Barkelsby

**Comment by bruecksen** [comment]
@madmooose ich verstehe das problem, aber nicht die vorgeschlagene Lösung ;)

**Comment by bruecksen** [comment]
@madmooose ich hab das ganze mal etwas optimiert. Mobile werden jetzt die buttons hinter einem kleinen Download button versteckt. Ab einer gewissen display größe wird dann ggf. ein Button mit optional dropdown angezeigt. So ist jetzt auch der Abbrechen Button etwas versteckt und kann nicht so einfach geklickt werden. Sag gerne was du davon hälst oder erkläre mir nochmal deinen Lösungsvorschlag. Hab aber auch bissl rumexperimentiert und alles andere sah blöd aus oder hat nicht gut funktioniert.
