### ISSUE TITLE
Add production day creation to workshop

### ISSUE THREAD

**Issue by madmooose** [bruecksen/bakeup#49]
- [x] Add new production days and their products
- [x] Edit production days and check for collision with existing orders or lock editing days with orders

**Comment by bruecksen** [comment]
@madmooose nice production day creation/update views incoming... https://bakeup.org/workshop/production-days/

@madmooose should we move collision detection in another ticket and milestone? Guess its not necessary in 0.2

**Comment by madmooose** [comment]
For now i would suggest making things uneditable as soon as orders exit. We need some kind of locking,

**Comment by madmooose** [comment]
But it would be nice to be able to add products on existig baking days. should we move this to 0.3?

**Comment by bruecksen** [comment]
@madmooose yes, could you open a new ticket for 0.3?
