### ISSUE TITLE
[imp] add order via worskhop to a production day

### ISSUE THREAD

**Issue by bruecksen** [bruecksen/bakeup#493]
Make it possible for bakers to add an order in the workshop to a production day.

**Comment by bruecksen** [comment]
@madmooose Ich habe das mal umgesetzt und auf staging deployed. Die bisherige batch update/create view hat ja überhaupt nicht auf den Produktionsstatus geachtet. Du konntest also bestellungen für produkte hinzufügen/löschen auch wenn das schon produziert wurde.  Das ist jetzt bei der view auch erstmal der Fall. Ich will es nicht zu kompliziert machen, aber was denkst du wäre ein guter kompromiss? So lassen und einen Nachricht anzeigen wenn eins der Produkte nicht mehr im planned status ist? Oder hast du einen anderen Vorschlag?

Du kannst jetzt hier https://staging.bakeup.org/workshop/production-days/44/ neben Ändere Bestellungen auch einen hinzufügen.

**Comment by madmooose** [comment]
Find ich gut bis auf mobile

Am 14. Juni 2024 04:00:33 MESZ schrieb "Matthias Brück" ***@***.***>:
>@madmooose Ich habe das mal umgesetzt und auf staging deployed. Die bisherige batch update/create view hat ja überhaupt nicht auf den Produktionsstatus geachtet. Du konntest also bestellungen für produkte hinzufügen/löschen auch wenn das schon produziert wurde.  Das ist jetzt bei der view auch erstmal der Fall. Ich will es nicht zu kompliziert machen, aber was denkst du wäre ein guter kompromiss? So lassen und einen Nachricht anzeigen wenn eins der Produkte nicht mehr im planned status ist? Oder hast du einen anderen Vorschlag?
>
>Du kannst jetzt hier https://staging.bakeup.org/workshop/production-days/44/ neben Ändere Bestellungen auch einen hinzufügen.
>
>-- 
>Reply to this email directly or view it on GitHub:
>https://github.com/bruecksen/bakeup/issues/493#issuecomment-2167073547
>You are receiving this because you were mentioned.
>
>Message ID: ***@***.***>
-- mobil gesendet
Niels Göttsch
Gut Hemmelmark 5
24360 Barkelsby

**Comment by madmooose** [comment]
Wegen dem editing. Ich finde es im Backend nicht so wild. Menschen mit Backend Zugang sollten wissen, was sie tun.
Nr Warnmeldungen, die man dann bestätigen muss oder zum edit zurückkehren kann, ist aber natürlich gut, um eventuelle eingabefehler zu vermeiden.

Am 14. Juni 2024 04:00:33 MESZ schrieb "Matthias Brück" ***@***.***>:
>@madmooose Ich habe das mal umgesetzt und auf staging deployed. Die bisherige batch update/create view hat ja überhaupt nicht auf den Produktionsstatus geachtet. Du konntest also bestellungen für produkte hinzufügen/löschen auch wenn das schon produziert wurde.  Das ist jetzt bei der view auch erstmal der Fall. Ich will es nicht zu kompliziert machen, aber was denkst du wäre ein guter kompromiss? So lassen und einen Nachricht anzeigen wenn eins der Produkte nicht mehr im planned status ist? Oder hast du einen anderen Vorschlag?
>
>Du kannst jetzt hier https://staging.bakeup.org/workshop/production-days/44/ neben Ändere Bestellungen auch einen hinzufügen.
>
>-- 
>Reply to this email directly or view it on GitHub:
>https://github.com/bruecksen/bakeup/issues/493#issuecomment-2167073547
>You are receiving this because you were mentioned.
>
>Message ID: ***@***.***>
-- mobil gesendet
Niels Göttsch
Gut Hemmelmark 5
24360 Barkelsby

**Comment by madmooose** [comment]
What about hiding the add product AS long AS no customer ist selected. Then we can load existing orders on selection

**Comment by bruecksen** [comment]
> What about hiding the add product AS long AS no customer ist selected. Then we can load existing orders on selection

that would be nice but is to much js frickelei at the moment. I could imagine doing that at a later point once we introduced a proper way to handle all the dynamic parts in bakeup ;)

**Comment by bruecksen** [comment]
@madmooose an info message is now shown and customers with orders are deactivated in the dropdown.
