### ISSUE TITLE
[imp] Add show unsubscribe option to newsletter page 

### ISSUE THREAD

**Issue by bruecksen** [bruecksen/bakeup#522]
- show_unsubscribe should default to True
- If True should add the unsubscribe option to the email footer otherwise not

**Comment by madmooose** [comment]
@bruecksen is it good to habe this optional? I thougjt it's a legal requirement.

**Comment by bruecksen** [comment]
> @bruecksen is it good to habe this optional? I thougjt it's a legal requirement.

yes but you know customers want stuff even if it is illegal :P
