### ISSUE TITLE
make workshop products products again

### ISSUE THREAD

**Issue by madmooose** [bruecksen/bakeup#79]
Products still points to ingredients but ingredients is just a filter for products.
Should be the other way round as it defaults to products (which is now shown as recipies).
ex. if you delete a product (coming from ingredients) it returns to products (called recipies)
Better make recipies a filter for products

**Comment by bruecksen** [comment]
@madmooose i started working on this :)

**Comment by madmooose** [comment]
https://github.com/bruecksen/bakeup/commit/cbd2835ea8ef35745ec66d8b547d1153ebbdc530

**Comment by madmooose** [comment]
Still have to get used to that workflow. Simply forgot to tag this issue and close it.
