### ISSUE TITLE
Multilanguage

### ISSUE THREAD

**Issue by bruecksen** [bruecksen/bakeup#8]
Should we start with german and english or simply start with german and translate later? @madmooose What do you think?

**Comment by madmooose** [comment]
Start with english and translate to german but soon (more like immediately) if you have a tutorial to read up the django way please share

**Comment by bruecksen** [comment]
yes I guess we need both. At least albatross is english - so we wouldn't have a german only audience. The django way is to write everything in english and use the translation string in code and template. Then at one point we generate translation files and translate everything into german.

https://docs.djangoproject.com/en/4.0/topics/i18n/translation/#standard-translation

```
from django.http import HttpResponse
from django.utils.translation import gettext as _

def my_view(request):
    output = _("Welcome to my site.")
    return HttpResponse(output)
```

and in Templates:

```
{% load i18n %} 
...
<title>{% translate "This is the title." %}</title>
```

**Comment by madmooose** [comment]
So should we go through all files and do this. it's getting more and more work, to do it later, right?

**Comment by bruecksen** [comment]
@madmooose yes you are right the sooner the better. Lets start with this!
