### ISSUE TITLE
Add normalize button to recipe editor

### ISSUE THREAD

**Issue by madmooose** [bruecksen/bakeup#87]

**Comment by bruecksen** [comment]
@madmooose es gibt jetzt einen normalize button. Das verändert aber nur die quantity aller Produkte auf der aktuellen Ebene. Es wandert den Baum also nicht hoch oder runter. Runter wandern wäre auch übel, weil es tausende andere Rezepte verändern würde, Hoch wandern sollte eigentlich gehen oder? Aber was würdest du erwarten was der button macht?

**Comment by madmooose** [comment]
Genau richtig, du kannst unterrezepte ja auch gar nicht im rezeptview ändern

Am 29. Juni 2022 10:48:16 MESZ schrieb "Matthias Brück" ***@***.***>:
***@***.*** es gibt jetzt einen normalize button. Das verändert aber nur die quantity aller Produkte auf der aktuellen Ebene. Es wandert den Baum also nicht hoch oder runter. Runter wandern wäre auch übel, weil es tausende andere Rezepte verändern würde, Hoch wandern sollte eigentlich gehen oder? Aber was würdest du erwarten was der button macht?
>
>
>
>-- >
>Reply to this email directly or view it on GitHub:
>
>https://github.com/bruecksen/bakeup/issues/87#issuecomment-1169705255
>
>You are receiving this because you were mentioned.
>
>
>
>Message ID: ***@***.***>
-- mobil gesendet
Niels Göttsch
Gut Hemmelmark 5
24360 Barkelsby
+49 177 1961512

**Comment by madmooose** [comment]
I think we should just edit one layer. Else we have to deal with to many unforseen sideeffects. 
Could you have a look here. https://bakeup.org/workshop/products/6/
If you press normalize it reduces the total amount but changes the ratio between parent product and sum of total ingredients. if you press it a few times it seems to narrow but this is not how it should be. Maybe we could make the total amount field percentage and editable. This way we could ajust the "gärverlust"

**Comment by madmooose** [comment]
ok, just had a closer look. it doesn't seem to change the value of products with childs (like other doughs)

**Comment by madmooose** [comment]
works, but I think we implement this one as adjustment of the Gärverlust/zuschlagmenge
